//! Trait for types that can be serialized/deserialized with the Crous format.
//!
//! This is the trait generated by `#[derive(Crous)]`. It provides schema-bound
//! encoding with stable field IDs and schema fingerprints.

use crate::error::Result;
use crate::value::Value;

/// Trait for types that can encode/decode to/from the Crous binary format.
///
/// Implementations are typically generated by `#[derive(Crous)]` from
/// the `crous-derive` crate, which assigns stable field IDs and computes
/// schema fingerprints.
///
/// # Example (manual implementation)
/// ```
/// use crous_core::{Crous, Value};
///
/// struct Point { x: f64, y: f64 }
///
/// impl Crous for Point {
///     fn to_crous_value(&self) -> Value {
///         Value::Object(vec![
///             ("x".into(), Value::Float(self.x)),
///             ("y".into(), Value::Float(self.y)),
///         ])
///     }
///
///     fn from_crous_value(value: &Value) -> crous_core::Result<Self> {
///         match value {
///             Value::Object(fields) => {
///                 let mut x = 0.0;
///                 let mut y = 0.0;
///                 for (k, v) in fields {
///                     match k.as_str() {
///                         "x" => x = v.as_float().unwrap_or(0.0),
///                         "y" => y = v.as_float().unwrap_or(0.0),
///                         _ => {} // skip unknown fields for forward compat
///                     }
///                 }
///                 Ok(Point { x, y })
///             }
///             _ => Err(crous_core::CrousError::SchemaMismatch(
///                 "expected object for Point".into()
///             )),
///         }
///     }
///
///     fn schema_fingerprint() -> u64 { 0x1234567890abcdef }
///     fn type_name() -> &'static str { "Point" }
/// }
/// ```
pub trait Crous: Sized {
    /// Convert this value to an owned `Value` for encoding.
    fn to_crous_value(&self) -> Value;

    /// Construct this type from a decoded `Value`.
    fn from_crous_value(value: &Value) -> Result<Self>;

    /// A stable fingerprint (XXH64) of this type's schema.
    /// Used for schema-on-write validation.
    fn schema_fingerprint() -> u64;

    /// The human-readable type name for diagnostics.
    fn type_name() -> &'static str;

    /// Encode this value directly to Crous binary bytes.
    ///
    /// Convenience method that creates an `Encoder`, encodes the value,
    /// and returns the finished byte vector.
    fn to_crous_bytes(&self) -> Result<Vec<u8>> {
        let val = self.to_crous_value();
        let mut enc = crate::encoder::Encoder::new();
        enc.encode_value(&val)?;
        enc.finish()
    }

    /// Decode from Crous binary bytes using default limits.
    fn from_crous_bytes(data: &[u8]) -> Result<Self> {
        let mut dec = crate::decoder::Decoder::new(data);
        let val = dec.decode_next()?.to_owned_value();
        Self::from_crous_value(&val)
    }

    /// Decode from Crous binary bytes with custom limits.
    ///
    /// This enforces all `Limits` during binary decode: nesting depth,
    /// memory, block size, string length, and item count.
    fn from_crous_bytes_with_limits(data: &[u8], limits: crate::limits::Limits) -> Result<Self> {
        let mut dec = crate::decoder::Decoder::with_limits(data, limits);
        let val = dec.decode_next()?.to_owned_value();
        Self::from_crous_value(&val)
    }
}

// --- Blanket impls for common types ---

impl Crous for String {
    fn to_crous_value(&self) -> Value {
        Value::Str(self.clone())
    }

    fn from_crous_value(value: &Value) -> Result<Self> {
        match value {
            Value::Str(s) => Ok(s.clone()),
            _ => Err(crate::error::CrousError::SchemaMismatch(
                "expected string".into(),
            )),
        }
    }

    fn schema_fingerprint() -> u64 {
        0x0001
    }
    fn type_name() -> &'static str {
        "String"
    }
}

impl Crous for u64 {
    fn to_crous_value(&self) -> Value {
        Value::UInt(*self)
    }

    fn from_crous_value(value: &Value) -> Result<Self> {
        match value {
            Value::UInt(n) => Ok(*n),
            _ => Err(crate::error::CrousError::SchemaMismatch(
                "expected uint".into(),
            )),
        }
    }

    fn schema_fingerprint() -> u64 {
        0x0002
    }
    fn type_name() -> &'static str {
        "u64"
    }
}

impl Crous for i64 {
    fn to_crous_value(&self) -> Value {
        Value::Int(*self)
    }

    fn from_crous_value(value: &Value) -> Result<Self> {
        match value {
            Value::Int(n) => Ok(*n),
            _ => Err(crate::error::CrousError::SchemaMismatch(
                "expected int".into(),
            )),
        }
    }

    fn schema_fingerprint() -> u64 {
        0x0003
    }
    fn type_name() -> &'static str {
        "i64"
    }
}

impl Crous for bool {
    fn to_crous_value(&self) -> Value {
        Value::Bool(*self)
    }

    fn from_crous_value(value: &Value) -> Result<Self> {
        match value {
            Value::Bool(b) => Ok(*b),
            _ => Err(crate::error::CrousError::SchemaMismatch(
                "expected bool".into(),
            )),
        }
    }

    fn schema_fingerprint() -> u64 {
        0x0004
    }
    fn type_name() -> &'static str {
        "bool"
    }
}

impl Crous for f64 {
    fn to_crous_value(&self) -> Value {
        Value::Float(*self)
    }

    fn from_crous_value(value: &Value) -> Result<Self> {
        match value {
            Value::Float(f) => Ok(*f),
            _ => Err(crate::error::CrousError::SchemaMismatch(
                "expected float".into(),
            )),
        }
    }

    fn schema_fingerprint() -> u64 {
        0x0005
    }
    fn type_name() -> &'static str {
        "f64"
    }
}

impl<T: Crous> Crous for Vec<T> {
    fn to_crous_value(&self) -> Value {
        Value::Array(self.iter().map(|item| item.to_crous_value()).collect())
    }

    fn from_crous_value(value: &Value) -> Result<Self> {
        match value {
            Value::Array(items) => items.iter().map(T::from_crous_value).collect(),
            _ => Err(crate::error::CrousError::SchemaMismatch(
                "expected array".into(),
            )),
        }
    }

    fn schema_fingerprint() -> u64 {
        // Combine with element type's fingerprint.
        T::schema_fingerprint()
            .wrapping_mul(31)
            .wrapping_add(0x0010)
    }

    fn type_name() -> &'static str {
        "Vec"
    }
}

impl<T: Crous> Crous for Option<T> {
    fn to_crous_value(&self) -> Value {
        match self {
            Some(v) => v.to_crous_value(),
            None => Value::Null,
        }
    }

    fn from_crous_value(value: &Value) -> Result<Self> {
        match value {
            Value::Null => Ok(None),
            other => Ok(Some(T::from_crous_value(other)?)),
        }
    }

    fn schema_fingerprint() -> u64 {
        T::schema_fingerprint()
            .wrapping_mul(37)
            .wrapping_add(0x0020)
    }

    fn type_name() -> &'static str {
        "Option"
    }
}
